# Generated by Django 3.1.3 on 2021-02-12 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Core_Cohort',
            fields=[
                ('cohort_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('core_cohort', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'core_cohort',
            },
        ),
        migrations.CreateModel(
            name='Prep_Cohort',
            fields=[
                ('cohort_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('prep_cohort', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'prep_cohort',
            },
        ),
        migrations.CreateModel(
            name='Student_Profile',
            fields=[
                ('student_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('age', models.IntegerField(null=True)),
                ('dob', models.DateField()),
                ('phone', models.IntegerField(null=True)),
                ('core_cohort', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admissions.core_cohort')),
                ('prep_cohort', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admissions.prep_cohort')),
            ],
            options={
                'db_table': 'Student_Profile',
            },
        ),
        migrations.CreateModel(
            name='Student_Education_Background',
            fields=[
                ('edu_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('education_level', models.CharField(max_length=50)),
                ('university', models.CharField(max_length=50)),
                ('university_course', models.CharField(max_length=50)),
                ('employed_before', models.CharField(max_length=50)),
                ('employer', models.CharField(max_length=50)),
                ('employed_net_salary', models.CharField(max_length=50)),
                ('gross_income_guardian', models.CharField(max_length=50)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admissions.student_profile')),
            ],
            options={
                'db_table': 'Student_Education_Background',
            },
        ),
    ]
