# Generated by Django 3.1.3 on 2021-02-12 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Post_Moringa',
            fields=[
                ('post_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('graduation_date', models.DateField()),
                ('developer_profile', models.CharField(max_length=50)),
                ('company_after_ms', models.CharField(max_length=50)),
                ('job_title', models.CharField(max_length=50)),
                ('fulltime_internship', models.CharField(max_length=50)),
                ('salary_after_ms', models.IntegerField(null=True)),
                ('sec_salary_after_ms', models.IntegerField(null=True)),
                ('comments_post_call', models.IntegerField(null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admissions.student_profile')),
            ],
            options={
                'db_table': 'Student_Post_Moringa',
            },
        ),
    ]
